### ISSUE TITLE
How to uninstall robostack ros2 on m1 mac?

### ISSUE THREAD

**Issue by Thomas-Yip** [RoboStack/ros-humble#93] opened 2023-08-12 17:38 UTC
I followed robostack instruction and installed ros2 on my m1 mac. My mac can run turtlesim. However, after I created a package in my ros2 worksapace, I colcon build the package and it turned out it could not be run. Should I uninstall ros2 and install it again?

**Comment by Tobias-Fischer** [comment] 2023-08-12 20:12
Duplicate of #94

**Closed by Tobias-Fischer** 2023-08-12 20:12 UTC
